Components
sevinchek/math-magicians pull request #2
Opened 2021-08-10 21:51 UTC by sevinchek

In this branch I:

- Created a component in a different JS file
- Imported the component in the App.js
- Added style to created component
- Updated Linters

2021-08-10 22:12 UTC, sevinchek commented
Hi, reviewer. I don't know why the linters are not appearing.

2021-08-10 22:28 UTC, DeliceLydia commented
# Status: Invalid

Hello @sevinchek,

I can see you worked hard but I can't review your project because no linter checks
available now please follow this [link](https://github.com/microverseinc/linters-config/tree/master/react-redux) step by step to configure it well and then submit another CRR

Thank you!

2021-08-10 22:37 UTC, initseis commented
Hi, @DeliceLydia. I already resolved it.

2021-08-11 00:23 UTC, arslanbisharat requested changes
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-11 00:23 UTC, arslanbisharat commented on src/App.css
> +#percentage {
- [ ] Try to avoid using ID aa a selector. You can use classes instead.

2021-08-11 00:23 UTC, arslanbisharat commented on src/App.css
> +#division {
- [ ] Try to avoid using ID aa a selector. You can use classes instead.

2021-08-11 00:23 UTC, arslanbisharat commented on src/App.css
> +#seven {
- [ ] Try to avoid using ID aa a selector. You can use classes instead.

2021-08-11 00:23 UTC, arslanbisharat commented on src/App.css
> +#eight {
- [ ] Try to avoid using ID aa a selector. You can use classes instead.

2021-08-11 00:23 UTC, arslanbisharat commented on src/App.css
> +#nine {
- [ ] Try to avoid using ID aa a selector. You can use classes instead.

2021-08-11 00:23 UTC, arslanbisharat commented on src/App.css
> +#by {
- [ ] Try to avoid using ID aa a selector. You can use classes instead.

2021-08-11 00:23 UTC, arslanbisharat commented on src/App.css
> +#equal {
- [ ] Try to avoid using ID aa a selector. You can use classes instead.

2021-08-11 00:23 UTC, arslanbisharat commented on src/App.css
> +#dot {
- [ ] Try to avoid using ID aa a selector. You can use classes instead.

2021-08-11 00:23 UTC, arslanbisharat commented on src/App.css
> +#zero {
- [ ] Try to avoid using ID aa a selector. You can use classes instead.

2021-08-11 00:23 UTC, arslanbisharat commented on src/App.js
>  export default App;
- [ ] App js should have a class based component. Please work on it.

2021-08-11 03:20 UTC, Davidosky007 approved these changes
## Hi @sevinchek 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-11 03:20 UTC, Davidosky007 commented on src/App.js
> +// }
## [OPTIONAL]
* I strongly suggest you remove commented code it makes your codebase bulky and unprofessional

2021-08-11 03:27 UTC, sevinchek commented
Thanks, @Davidosky007.

2021-08-11 03:28 UTC, merged